title: 코드나무 커뮤니티
description: |
  코드나무는 공공정보 개방은 정부의 투명성을 높이고 새로운 부가가치를 만들어 낼 뿐만 아니라 무엇보다도 시민들의 참여를 통해서 새로운 혁신, 새로운 공공가치의 창조를 이끌어낼수 있다고 믿습니다. 코드나무와 같이 시민들의 지속적이고 자발적인 참여가 시민들의 참여를 끌어내고 실현시킬 수 있는 플랫폼을 구축하고 적극적으로 참여할 수 있는 문화를 바꿀 수 있다고 믿습니다. 코드나무는 정부를 탓하기 보다는 우리가 직접 보여줄 수 있는 프로젝트를 통해서 시민과 정부가 협력할 수 있는 모델을 만들고자 합니다.
keywords: |
  "열린 정부, open government, 시빅해킹, civic hacking, 코드포서울, code for seoul, 공공데이터, open data, 데이터, data"
permalink: /:year/:month/:day/:title

gems:
  - jekyll-paginate

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    Asia/Seoul
future:      true
highlighter: pygments
markdown:    kramdown
paginate:    5
paginate_path: "/blog/page:num/"

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

  coderay:
    coderay_line_numbers:
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: class

featured_posts:
  -
    title: "고위공직자 재산 공개 웹사이트, 이렇게 만들어졌다"
    description: "2016년 외부 협력 첫번째 프로젝트로 뉴스타파와 협력하여 '고위공직자 재산 공개' 웹사이트를 구축했습니다. 이 사이트의 개발 과정과 그 이후 생각들을 정리해보았습니다."
    date: "2016-06-10"
    link: "http://codenamu.org/2016/06/08/behind-story-jaesan-newstapa"
  -
    title: "GPL, AGPL, MPL... 한눈에 보는 오픈소스SW 라이선스"
    description: "대표적인 오픈소스 라이선스들을 알아보고, 특징과 조건들을 비교해보았습니다. 적용 사례도 소개합니다. 앞으로는 오픈소스 SW를 활용하거나 오픈소스 SW를 만들 때 라이선스에 대해 한 번쯤 고민할 수 있는 계기가 됐으면 좋겠습니다."
    date: "2014-10-10"
    link: "http://codenamu.org/2014/10/10/popular-opensource-license"
  -
    title: "대한민국 세금 데이터, '해킹'해봤어요"
    description: "대한민국 세출 데이터를 활용하여 내가 낸 세금이 어떤 분야에 얼만큼 쓰이는지 알 수 있는 'Where Does My Money Go?'. 이 사이트의 개발 과정을 정리들려드립니다."
    date: "2014-08-18"
    link: "http://codenamu.org/2014/08/18/hacked-tax-data"

partners:
  -
    name: "CCKOREA"
    slug: "cckorea"
    img: "cckorea_logo.png"
    link: "http://cckorea.org"
  -
    name: "Code for All"
    slug: "code-for-all"
    img: "codeforall.png"
    link: "http://codeforall.org"
  -
    name: "Code for America"
    slug: "code-for-america"
    img: "cfa_logo_lg.png"
    link: "http://codeforamerica.org"
  -
    name: "Code for Germany"
    slug: "code-for-germany"
    img: "codeforgermany.png"
    link: "http://codefor.de/"
  -
    name: "Code for Seoul"
    slug: "code-for-seoul"
    img: "cfs_logo.png"
    link: "http://codeforseoul.org"
  # -
  #   name: "Open Knowledge International"
  #   slug: "oki"
  #   img: "oki.png"
  #   link: "http://okfn.org"
  # -
  #   name: "그린피스 한국"
  #   slug: "greanpeace-korea"
  #   img: "greenpeace.jpg"
  #   link: "http://www.greenpeace.org/korea/"
  # -
  #   name: "뉴스타파"
  #   slug: "newstapa"
  #   img: "newstapa.png"
  #   link: "http://newstapa.org"
  # -
  #   name: "중앙일보"
  #   slug: "joins"
  #   img: "joins.png"
  #   link: "http://joins.com"
  # -
  #   name: "참여연대"
  #   slug: "pspd"
  #   img: "pspd.jpg"
  #   link: "http://www.peoplepower21.org/"

prose:
  rooturl: '_posts'
  siteurl: 'http://prose.github.io/starter/'
  relativeLinks: 'http://prose.github.io/starter/links.jsonp'
  media: '_post/media'
  metadata:
    _posts:
      - name: "category"
        field:
          element: "multiselect"
          value: "Add Category"
          placeholder: "Choose Category"
          options:
            - name: "블로그"
              value: "blog"
            - name: "공지사항"
              value: "notice"
            - name: "외부소식"
              value: "news"
            - name: "코드포서울"
              value: "code-for-seoul"
            - name: "춘식이의 코드이야기"
              value: "codestory"
      - name: "layout"
        field:
          element: "hidden"
          value: "blog"
      - name: "title"
        field:
          element: "text"
          label: "Title"
          value: ""
      - name: "splash"
        field:
          element: "text"
          label: "Splash image"
          value: ""
      - name: "tags"
        field:
          element: "multiselect"
          label: "Add Tags"
          alterable: true
          placeholder: "Choose Tags"
          options:
    _posts/static:
      - name: "layout"
        field:
          element: "hidden"
          value: "page"
      - name: "title"
        field:
          element: "text"
          label: "Title"
          value: ""
      - name: "permalink"
        field:
          element: "text"
          label: "Permalink"
          value: ""
